### ISSUE TITLE
Migration from SiriAPI

### ISSUE THREAD

**Issue by xena68** [HcDevel/SiriAPI8#1]
First of all -- Thank You!  I can't wait to try it out this weekend!

Second -- are there any instructions on migrating from the older SiriAPI to SiriAPI8?  I invested a lot into the old version and still use it via Voice Commands.  Can't wait to get back to using with Siri!

Thanks

**Comment by RobinMeis** [comment]
Nice to see the first users of SiriAPI8. I haven't migrated my commands yet and currently I don't provide any migration instructions. I planned them but then I completely forgot before the release..
Wildcards shouldn't have changed because I just copied & pasted many parts of the search code. So you will not have to create new commands. Just the way how they are defined has changed.
I'll need to check the old source code because I'm currently not shure how it exactly worked ;) but I'm looking forward to provide the instructions within the next days.

**Comment by RobinMeis** [comment]
I added migration information in the wiki: https://github.com/HcDevel/SiriAPI8/wiki/Migration-from-SiriAPI-to-SiriAPI8. If you have some more questions concering the migration please reopen this issue.
