### ISSUE TITLE
iOS 9 compatibility

### ISSUE THREAD

**Issue by reptil1990** [HcDevel/SiriAPI8#25]
I have iOS9 installed i get this response from the example:
SiriAPI8 error: No action defined for < html>< head>< /head>< body>< div>iPhone hallo Carsten< /div>  < /body>< /html>

Are there some changes needed for the search engine?

**Comment by RobinMeis** [comment]
I think iOS9 brought some updates to the notes app. I remember that there was a problem with notes created on a Mac because they contained html. It seems Apple uses html to improve the notes app and add additional objects such as images (http://appleinsider.com/articles/15/06/12/inside-ios-9-apples-notes-app-is-greatly-enhanced-with-drawings-lists-pictures-links-more). It shouldn’t be to hard to remove the HTML tags from a message.

**Comment by RobinMeis** [comment]
I solved the problem. New version will be released soon.

**Comment by RobinMeis** [comment]
It would be great if you could test the release and give me some feedback. The latest version is now online

**Comment by RobinMeis** [comment]
SiriAPI 8 ist not compatible with iOS 9

**Comment by MacBookeur** [comment]
Is il compatible soon or never ?
Thanks for your good job

**Comment by RobinMeis** [comment]
There might be a solution but currently it is not planned to make SiriAPI8 iOS 9 compatible.

**Comment by MacBookeur** [comment]
Ok.
It works like a charm on ios8, I create a lot of scripts to control VMware, iTunes, ad...
It's very useful!

I would like to work on ios9, if you don't have time, can I help you ?

Envoyé de mon iPhone

**Comment by RobinMeis** [comment]
Currently I have no idea how to create a version for iOS 9. This might change in future, but I think currently it  is easier to use "Homebridge" which can already interface between FHEM and Homekit. It integrates better into Siri than SiriAPI ever could.
