### ISSUE TITLE
two factor

### ISSUE THREAD

**Issue by matbor** [HcDevel/SiriAPI8#27]
Will this work if you have two-factor authentication turned on? I guessing that is why it comes back to me saying, 

`Exception: Login to iCloud failed. Check user credentials`

even though I have entered the correct userrname/password into `example.py`.

**Comment by matbor** [comment]
can get the repo, pyicloud to work fine. Just having problems with your one.

**Comment by RobinMeis** [comment]
SiriAPI8 is completely different from pyicloud. Pyicloud accesses the HTTP frontend of the iCloud, which might not be a good idea, since Apple can easily modify their iCloud frontend.
SiriAPI8 ist using IMAP to read your notes. Since IMAP is a specified standard, Apple can't change anything there. This is why SiriAPI8 also doesn't support two factor authentification.
I never used two factor authentification but I think you will need to set an application password: https://support.apple.com/en-us/HT204397

**Comment by RobinMeis** [comment]
No resonse - closed
